version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  
  build:
    commands:
      - echo Build started on `date`
      - npm run lint
      - npm test
  
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p dist
      - cp index.js dist/
      - cp package.json dist/
      - cd dist && npm install --production

artifacts:
  files:
    - dist/**/*
  base-directory: '.'