version: 0.2

env:
  variables:
    NODE_ENV: "production"
  parameter-store:
    DYNAMODB_TABLE: "/foodtruckfinder/dynamodb-table-name"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  
  pre_build:
    commands:
      - echo Running pre-build checks...
      - npm run lint
      - npm test
  
  build:
    commands:
      - echo Build started on `date`
      - echo Setting build version...
      - export BUILD_VERSION=$(date +%Y%m%d%H%M%S)
      - echo "Building version $BUILD_VERSION"
      - mkdir -p dist
      - cp index.js dist/
      - cp package.json dist/
      - echo '{"version": "'$BUILD_VERSION'", "table": "'$DYNAMODB_TABLE'"}' > dist/config.json
      - cd dist && npm install --production
  
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR
      - zip -r function.zip dist/*

artifacts:
  files:
    - function.zip
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'