# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  
  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
  
  build:
    commands:
      - echo Building the TypeScript application...
      - npm run build
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running security audit...
      - npm audit --production

artifacts:
  files:
    - package.json
    - package-lock.json
    - dist/**/*
    - node_modules/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'