# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  
  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
  
  build:
    commands:
      - echo Building the TypeScript application...
      - npm run build
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running security audit...
      - npm audit --production
      - echo Running OWASP dependency check...
      - |
        if ! command -v dependency-check &> /dev/null; then
          echo "Installing OWASP Dependency-Check..."
          mkdir -p /tmp/dc
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -o /tmp/dc/dc.zip
          unzip /tmp/dc/dc.zip -d /tmp/dc
          chmod +x /tmp/dc/dependency-check/bin/dependency-check.sh
        fi
        /tmp/dc/dependency-check/bin/dependency-check.sh --scan . --out dependency-check-report.html || echo "Dependency check completed with warnings"
      - echo Running SonarQube scan...
      - |
        if [ -n "$SONAR_HOST_URL" ] && [ -n "$SONAR_TOKEN" ]; then
          echo "Running SonarQube scan..."
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=simple-typescript-app \
            -Dsonar.sources=. \
            -Dsonar.exclusions=node_modules/**,**/*.test.ts \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN
        else
          echo "Skipping SonarQube scan - environment variables not set"
        fi

artifacts:
  files:
    - package.json
    - package-lock.json
    - dist/**/*
    - node_modules/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'